config/routes.rb
MFTModule1::Application.routes.draw do

  devise_for :users, :controllers => {:confirmations => "xdevise/confirmations", :registrations => "registrations", :sessions=>"xdevise/sessions", :passwords => "devise/passwords"}, :skip=>[:sessions] do
    get "/users/confirmation", :to => "xdevise/confirmations#show"
    post "confirm_user", :to => "xdevise/confirmations#confirm_user"
    get 'signin' => 'xdevise/sessions#new', :as => :new_user_session
    post 'signin' => 'xdevise/sessions#create', :as => :user_session
    delete 'signout' => 'xdevise/sessions#destroy', :as => :destroy_user_session
    match 'users/auth/:provider/callback' => 'xdevise/sessions#omniauth', :via => :get
    match 'users/:provider/fb_twitter' => 'xdevise/sessions#fb_twitter', :via => :get
  end
  
  resources :ads do
    get '/optin', :to => 'ads#optin'
    member do
      post 'rate'
    end
  end
  
  resources :users
  resources :categories do
    member do
      delete 'destroy_category'
      get 'offers'
      get 'my_local_offers'
    end
  end
  resources :registrations
  resources :demos
  resources :optin_ads
  resources :groups

  
  resources :offers
  resources :authentications
  resources :demo_images
  resources :feedback

  resources :brands do
    member do
      get 'ads'
    end
  end

  scope "/admin" do
    resources :settings

    resources :brand_requests


  
    resources :templates
    
    match 'db'=>"templates#download_db"
    match 'master_password'=>'settings#master_password'
    match 'new_mpassword' => 'settings#new_mpassword'
    match '/setting/category_list' => 'settings#category_list'
    match '/setting/category_ads/:id' => 'settings#category_ads', :as => "category_ads"
    match '/setting/allusersads' => 'settings#allusersads'
    match '/setting/multipleads' => 'settings#multipleads'
    match '/setting/users_list' => 'settings#users_list'
    match '/setting/new_users' => 'settings#new_users'
    match '/setting/create_users' => 'settings#create_users'
    match '/setting/edit_users/:id' => 'settings#edit_users', :as => "edit_users"
    match '/setting/update_users/:id' => 'settings#update_users', :as => "update_users"
    match '/setting/destroy_users/:id' => 'settings#destroy_users', :as => "destroy_users"
    match '/setting/show_users/:id' => 'settings#show_users', :as => "show_users"
    match 'run/:format'=>"templates#run"


  end
  
  match "templates/delete_selection"=>"templates#delete_at_index"
  match "/my/sample/ind" => "ads#index"

  match 'delete_file'=>"templates#delete_file"
  match '/ads/flags_ad/:id'=>'ads#flags_ad'
  match '/ads/remove_ad/:id'=>'ads#remove_ad'
  match '/ads/ads_statuschange/:id'=>'ads#ads_statuschange', :as => "ads_statuschange"
  match '/ads/ads_statusunchange/:id'=>'ads#ads_statusunchange', :as => "ads_statusunchange"
  match '/offers/new_offer/:id' => 'offers#new_offer' , :as => "new_coupans"
  match '/offers/edit_coupan/:id' => 'offers#edit_coupan' , :as => "edit_coupans"
  match '/offers/update_coupan/:id' => 'offers#update_coupan' , :as => "update_coupans"
  match '/offers/state_city_list/:state_code' => 'offers#state_city_list'
  match '/ads/tabit_category_list' => 'ads#tabit_category_list'
  match '/user/settings' => 'users#settings'
  match '/optin_ads/save' => 'optin_ads#save'
  match '/optin_ads/refer' => 'optin_ads#refer'
  match '/demo/:id' => 'demos#demo'
  match '/ads/save'=>'ads#save'
  match '/ads/:id/test'=>'ads#test'

  match '/myfabtab' => 'ads#wrapper'
  match '/redirect' => 'redirection#redirect'
  match '/about' => 'home#about'
  match '/tabit' => 'home#tabit'
  match '/team' => 'home#team'
  match '/help' => 'home#help'
  match '/terms' => 'home#terms'
  match '/promo_help' => 'home#promo_help'
  match '/promo_tabit' => 'home#promo_tabit'
  match '/promo_terms' => 'home#promo_terms'
  match '/promo_team' => 'home#promo_team'
  match '/promo_create' => 'home#promo_create'
  match '/promo_invite' => 'home#promo_invite'
  match '/promo_create' => 'feedback#promo_create'
  match '/index' => 'home#index'
  match 'js/bookmarkads' => 'Js#bookmarkads'
  match '/search' => 'search#search'
  match '/search_username' => 'users#search_username'
  match '/status_change/:id' => 'users#status_change', :as => "status_change"
  match '/status_unchange/:id' => 'users#status_unchange', :as => "status_unchange"
  match '/adminstatus_change/:id' => 'users#adminstatus_change', :as => "adminstatus_change"
  match '/adminstatus_unchange/:id' => 'users#adminstatus_unchange', :as => "adminstatus_unchange"
  match '/predictive_search' => 'search#predictive_search'
  match '/invite' => 'users#invite'
  match '/invite/email' => 'users#email'
 
  match '/setting/destroy_ads/:id' => 'settings#destroy_ads', :as => "destroy_ads"
  match '/setting/destroy_userscategories/:id' => 'settings#destroy_userscategories', :as => "destroy_userscategories"
  match '/setting/ignore_notification/:id' => 'settings#ignore_notification', :as => "ignore_ad"
  match '/setting/flag_ads' => 'settings#flag_ads'
  match '/setting' => 'settings#parameters'
  match '/setting/multipleuser' => 'settings#multipleuser'
  match '/setting/sort_username' => 'settings#sort_username'

  match '/setting/destroy_fbtw/:id' => 'settings#destroy_fbtw' , :as => "destroy_fbtw"
  match '/admin/edit' => 'settings#edit'
  match '/follow_brand' => 'users#follow_brand'
  match '/my_local_offers_without_category' => 'categories#my_local_offers_without_category'
  get '/category_list' => 'categories#category_list'
  get '/local_storage_data' => 'categories#local_storage_data'
  match '/search_offers' => 'ads#search_offers'
  get '/search_offer_by_brand' => 'offers#search_offer_by_brand'
  match '/search_ads' => 'ads#search_ads'
  post '/snapit', :to => 'ads#snapit'
  get '/scanit', :to => 'ads#scanit'
  post 'ad_fb_comment/:ad_id/:fb_comment_id' => 'ads#ad_fb_comment'
  get '/ads_show/:ad_id', :to => 'ads#ads_show'
  get '/omniauth_fb/:uid/:email' => 'settings#omniauth_fb'
  get '/omniauth_tw/:uid' => 'settings#omniauth_tw'
  #  resources :templates do
  #
  #  end
  resources :purposes

  match 'unsubscribe_me' => "registrations#unsubscribe"

  match "templates/delete_selection"=>"templates#delete_at_index"


  get '/home/render_div'=>'home#render_div'

  root :to=> 'home#about'
end

app/views/templates/_clipboard_text.html.erb
<div>
  <u><b>Copy to Clipboard</b></u> <br/><br/>
<%= link_to_function "Lost password", "return copyToClipboard('{{lost_password}}')", :class => "copy" %><span class="login_links"> | </span>
<%= link_to_function "Confirmation link", "return copyToClipboard('{{confirmation_my_account}}')", :class => "copy" %><span class="login_links"> | </span>
<%= link_to_function "User name", "return copyToClipboard('{{user_name}}')", :class => "copy" %><span class="login_links"> | </span>
<%= link_to_function "User email", "return copyToClipboard('{{user_email}}')", :class => "copy" %><span class="login_links"> | </span>
<%= link_to_function "Admin email", "return copyToClipboard('{{admin_email}}')", :class => "copy" %><span class="login_links"> | </span>
<%= link_to_function "Offer image", "return copyToClipboard('{{ad_image_url}}')", :class => "copy" %><span class="login_links"> | </span>
<%= link_to_function "Offer selection", "return copyToClipboard('{{ad_token}}')", :class => "copy" %><span class="login_links"> | </span>
<%= link_to_function "Brand name", "return copyToClipboard('{{brand_name}}')", :class => "copy" %><span class="login_links"> | </span>
<%= link_to_function "Subscribe link", "return copyToClipboard('{{subscribe}}')", :class => "copy" %><span class="login_links"> | </span>
<%= link_to_function "Unsubscribe link", "return copyToClipboard('{{unsubscribe}}')", :class => "copy" %>
  
  <br/><br/>
</div>


<script type="text/javascript">
  function copyToClipboard (txt) {
    window.prompt("Copy to clipboard: Ctrl+C", txt);
  }
</script>
<style type="text/css">
  .login_links {
    color: #C3C6C5;
}
</style>

app/views/templates/_form.html.erb
<div class="brand_name">*Name</div> <br/>  <%= f.text_field :name %><br/><br/><br/><br/>
<div class="brand_name">*Purpose</div><br/>
<%= f.select(:purpose_id, Purpose.all.map{|p|[p.name, p.id]},:prompt=>"Select one") %>
<br/><br/><br/><br/>

<div class="alert_dialog hidden">
  <div class="title" style="margin-left: 14px;"> Do you want to save your changes otherwise<br/> it will be lost ?</div>
  <div class="message-text"> </div>
  <div class="con_links">
    <%= link_to "Cancel", '#',:onclick=>"closeIt();",  :id => 'add_coupan', :style=>'margin: 7px 0 0 312px;' %>
    <%= link_to "Confirm", templates_path,  :id => 'add_coupan', :style=>'margin: 45px 0px 0px 35px;' %>
  </div>
</div>
<div class="contect_area">
  <div class="brand_name">Content Area</div><br/>
  <%= f.text_area :content, :style=>"width: 100%;height: 100%;" %>
</div>
<br/><br/>
<style type="text/css">
  .nicEdit-main ol li{
    list-style:  inherit;
  }
  .nicEdit-main ul li{
    list-style:  inherit;
  }
  a:hover {
    color : #8BC541
  }
  a {
    color : #C3C6C5
  }
  .container footer {
    margin-top: 1px;
  }
  .search1 {
    display: none;
  }

  select,input[type="file"]{
    width: 260px;
  }
</style>
<script type="text/javascript">
  function closeIt(e){
    $('.alert_dialog').addClass('hidden');
    e.preventDefault();
  }
</script>

app/views/templates/_scripts.html.erb
<script type="text/javascript">
    

  $('#user_name').live('click',function(){
    var clip = new ZeroClipboard.Client("#user_name");
    //var clip = new ZeroClipboard.Client("#user_email");
    //clip.setText( "User name" );
    //
    //alert("clip : "+clip);
	alert("Try again!");
  });

  

  $('#user_email').live('click',function(){
    new ZeroClipboard.Client("#user_email");
	alert("Try again!");
  });

  $('#c_adminemail').live('click',function(){
    new ZeroClipboard.Client("#c_adminemail");
	alert("Try again!");
  });

  $('#c_offerimage').live('click',function(){
    new ZeroClipboard.Client("#c_offerimage");
	alert("Try again!");
  });

  $('#c_offerselection').live('click',function(){
    new ZeroClipboard.Client("#c_offerselection");
	alert("Try again!");
  });

  $('#c_brandname').live('click',function(){
    new ZeroClipboard.Client("#c_brandname");
	alert("Try again!");
  });

  $('#c_subscribelink').live('click',function(){
    new ZeroClipboard.Client("#c_subscribelink");
	alert("Try again!");
  });

  $('#c_unsubscribelink').live('click',function(){
    new ZeroClipboard.Client("#c_unsubscribelink");
	alert("Try again!");
  });

<%#*$('[id*=c_]').live('click',function(){%>
<%#*$(this).click();%>
<%#*id = $(this).attr('id').split('_')[1]%>
<%#*obj = "#"+id%>
<%#*new ZeroClipboard.Client(obj);%>
<%#*});%>
</script>

app/views/templates/download_db.html.erb
<div style="float: right;margin-right:10px; margin-top: 4px;">
  <%= link_to "Back",  admin_edit_path, :id=>"add_coupan" %>
</div>
<h2 style="font-size: 18px;color: #939598;font-weight: normal;margin-left: 7px;margin-top: 28px;">DATABASE DUMP FILE LIST</h2>


<div class="content" style="float: none;margin-left: -20px;">

  <br/>
  <br/>
  <div id ="dblist" >
    <% i = 0 %>
    <div class="total_db" >
      <div class="rows">
        <div class="tabal_div"style="width: 296px;float:left;margin-left: 27px;"><b>File Name</b></div>
        <div style="width: 120px;float:left;">&nbsp;</div>
        <div class="tabal_div" style="width: 180px;float:left; margin-left: -40px;margin-right: 23px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Actions</b></div>
        <div style="width: 90px;float:left;"> &nbsp;</div>
        <div class="tabal_div" style="width: 190px;float:left;"><b>Database Creation Date</b></div>
      </div>
      <div style="margin-top: 12px;height: 585px;overflow-x: hidden;overflow-y: scroll;width: 933px; float: left;">
        <% @bucket.objects.each do |obj| %>
          <% if obj.key.split('admin/')[1].split('/')[0].to_i == current_user.id %>
            <% if !(obj.key.split('admin/')[1].split('/')[1].nil?) %>
              <div class="row" id="firstscroll" style="padding: 0px 0 0;margin-bottom:11px;">
                <div style="width: 120px;float:left;">
                  <div class="delete_dialog hidden"style="margin: 10px 31px 20px 572px;" id="hidden_delete_box_<%=  i %>">
                    <div class="close" style="margin: 12px 24px;">X</div>
                    <div class="title" style="margin-left: 7px;"> Delete</div>
                    <div class="message-text"> Delete this file?</div>
                    <%= link_to "Delete", delete_file_path(:obj => obj.key), :method=>'delete', :class => 'delete_tab' %>
                  </div>
                </div>
                <div style="width: 296px;float:left;text-align: center;">
                  <%= rename_file(obj.key.split('admin/')[1].split('/')[1]) %>
                </div>
                <div style="width: 120px;float:left;">&nbsp;</div>
                <div style="width: 180px;float:left;text-align: center;">
                  <a href="<%= obj.url_for(:read,:expire => 10000*60) %>" >Download</a>&nbsp;<span class="login_link"> |</span> &nbsp;
                  <%= link_to_function "Delete", "$('#hidden_delete_box_#{i}').css('display','block');" %>
                  <% i = i+1 %>

                </div>
                <div style="width: 120px;float:left;">&nbsp;</div>
                <div style="width: 190px;float:left;">
                  <%= convert_time(obj.key.split('dump_')[1].split('.')[0]) %>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('.close').click(function(){
    $(this).parent().hide();
  });
</script>

<style type="text/css">
  a:hover {
    color : #8BC541
  }
  a {
    color : #C3C6C5
  }

  .container footer {
    margin-top: 25px;
  }
  .search1 {
    display: none;
  }

</style>

app/views/templates/edit.html.erb
<%= javascript_include_tag "nicEdit" %>
<%#= javascript_include_tag "ZeroClipboard" %>

<script type="text/javascript">
  //<![CDATA[
  bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
  //]]>

</script>
<%#= render :partial=> 'templates/scripts' %>

<div class="content" style="float: none;">

  <h1 style="font-size: 18px;color: #939598;font-weight: normal;margin-left: 3px;margin-top: 28px;">EDIT EMAIL TEMPLATE<span style="float: right;margin-right:10px;"> <%= link_to "All Templates", "#templates_path" , :id=>"add_coupan",:class=>"alerts" %></span></h1>
  <%= form_for(@template, :path=>template_path, :method=> "put") do |f| %>

    <%= render :partial=>"form", :locals=>{:f=>f } %>

    <%= f.submit "Update" , :id=>"add_coupan", :class=>'update_me' %>

    <%= link_to "Cancel", '#' , :id=>"add_coupan" ,:class=>"alerts" %>
  <% end %>

  <%= render :partial=>'templates/clipboard_text' %>

</div>
<script type="text/javascript">
  $('.alerts').on('click',function(e){
    $('.alert_dialog').removeClass('hidden');
    
    e.preventDefault();
  });

</script>

app/views/templates/index.html.erb
<%= javascript_include_tag 'templates' %>

<div class="content" style="float: none;">

  <h1 style="margin-left: 3px;font-size: 18px;color: #939598;font-weight: normal;margin-top: 28px;">EMAIL TEMPLATES LIST <span style="float: right; margin-top: -2px;margin-right:10px;">
      <%= link_to "Add New Template", new_template_path, :id=>"add_coupan", :class=>'space', :style=>'margin: 5px;' %><%= link_to "Back", admin_edit_path , :id=>"add_coupan" %></span></h1>
  <br/>
  <table class="table" style="border:none;color: #939598;font-size: 14px;">
    <th style="padding-left: 0px; padding-right: 32px; height: 19px; width: 36px; margin-left: 3px; margin-right: -3px; text-align: center;color: #939598;">
      <%= check_box_tag "delete[selected][]","all",false ,:id => "select_all"  %>
    </th>
    <th align="left" style="border-left: medium none ! important; padding-left: 0px; width: 206px; padding-right: 0px; height: 22px;color: #939598;">
      Template Name
    </th>
    <th style="border-left:none !important;  padding-right: 23px;">
      Purpose
    </th>
    <th align="left" style="border-left:none !important;">  </th>
    <th align="left" style="border-left:none !important;">
      &nbsp;&nbsp;Actions
    </th>
  </table>
  <%= form_tag(templates_delete_selection_path) do |f| %>
    <div style="margin-top: -12px;height: 550px;overflow-x: hidden;overflow-y: scroll;width: 933px; float: left;">
  <%#= link_to "List of Purpose", purposes_path %>
      <table class="table">
        <th style="display:none;"><%#= check_box_tag "delete[selected][]","all",false ,:id => "select_all"  %>&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th align="center" style="border-left:none !important;display:none;">&nbsp;&nbsp;&nbsp;&nbsp; </th>
        <th style="border-left:none !important;display:none;">&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th align="center" style="border-left:none !important;display:none;">  </th>
        <th align="center" style="border-left:none !important;display:none;">&nbsp;&nbsp;&nbsp;&nbsp;</th>

        <tbody>
          <% @templates.each do |f| %>
            <tr style="width:933px;">
              <td><%= check_box_tag "delete[selected][]",f.id ,false, :class=>"select_this" %></td>
              <td style="border-left:none !important;"><%= f.name %></td>
              <td style="border-left:none !important;"><%=  f.purpose.name %></td>
              <td style="border-left:none !important;">
                <div class="delete_dialog hidden" id="hidden_delete_box_<%=  f.id %>">
                  <div class="close" style="margin: 12px 24px;">X</div>
                  <div class="title" style="margin-left: 7px;"> Delete</div>
                  <div class="message-text"> Delete this Template?</div>
                  <%= link_to "Delete", template_path(f), :method=>'delete', :class => 'delete_tab' %>
                </div>
              </td>
              <td style="border-left:none !important;">
                <%= link_to "View", template_path(f)%> <span class="login_link"> | </span><%= link_to "Edit", edit_template_path(f) %><span class="login_link"> | </span>
                <%= link_to "Delete", "#",:onclick=>"show_delete_box(#{f.id})" ,:class => 'delete' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <%= submit_tag "Delete" , :id=>"delete_all", :style=>"top: 270px;position: absolute;" %>
  <% end %>

  <script type="text/javascript">


    $(".delete").live('click',function(e) {
      e.preventDefault()
    });
    function show_delete_box(id){
      $('#hidden_delete_box_'+id).css('display','block');
    }
    
    document.onload =  $("#delete_all").hide();

    $('.close').click(function(){
      $(this).parent().hide();
    });
    $('#select_all').click(function() {
      if (this.checked) {
        $(':checkbox').each(function() {
          this.checked = true;
        });
        $("#delete_all").show();
      } else {
        $(':checkbox').each(function() {
          this.checked = false;
        });
        $("#delete_all").hide();
      }
    });


    var count=0;

    $('.select_this').click(function() {
      if (this.checked) {
        count++;
        if(count > 0)
        {
          $("#delete_all").show();
        }
      }
      else
      {
        count--;
        if(count == 0)
        {
          $("#delete_all").hide();
        }
        else
        {
          $("#delete_all").show();
        }
      }
    });
  </script>
</div>


<style type="text/css">
  a:hover {
    color : #8BC541
  }
  a {
    color : #C3C6C5
  }
  /*
  .container footer {
    margin-top: 132px;
  }
  */
  table th {
    border-bottom: 0 solid #DDDDDD;
  }
  table {
    border: none;
  }

  table tr + tr td {
    border-top: none;
  }
  .search1 {
    display: none;
  }
</style>

app/views/templates/new.html.erb
<%= javascript_include_tag "nicEdit" %>
<%= javascript_include_tag "ZeroClipboard" %>
<script type="text/javascript">
  //<![CDATA[
  bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
  //]]>
  ZeroClipboard.setMoviePath( '/assets/ZeroClipboard.swf' );

</script>
<div style="float: right;margin-right:10px; margin-top: 3px;">
  <%= link_to "All Email Templates",  "#", :id=>"add_coupan",:class=>"alerts" %>
</div>
<%#= render :partial=> 'templates/scripts' %>

<div class="content" style="float: none;">


  <h2 style="font-size: 18px;color: #939598;font-weight: normal;margin-top: 28px;margin-left: 3px;">NEW TEMPLATE</h2>

  <%= form_for(@template, :path=>templates_path) do |f| %>
    <%= render :partial=>"form", :locals=>{:f=>f} %>
    <%= f.submit "Create", :id=>"add_coupan", :class=>'update_me' %>
    <%= link_to "Cancel", '#', :id=>"add_coupan" ,:class=>"alerts" %>
  <% end %>
  <%= render :partial=>'templates/clipboard_text' %>

</div>

<style type="text/css">
  .container footer {
    margin-top: 35px;
  }
  .search1 {
    display: none;
  }
</style>
<script type="text/javascript">
  $('.alerts').on('click',function(e){
    $('.alert_dialog').removeClass('hidden');

    e.preventDefault();
  });

</script>

app/views/templates/show.html.erb
<%= link_to "Back",templates_path,:id => "add_coupan", :style => "float: right;margin-top: 3px; margin-right: 10px;" %>
<div class="content" style="float: none;">


<h1 style="font-size: 18px;color: #939598;font-weight: normal;margin-top: 28px;margin-left: 4px;">VIEW EMAIL TEMPLATE</h1>

  Name : <%= @template.name %><br/>
  Purpose : <%= @template.purpose.name %><br/>
  Content : <%= @template.content.html_safe %><br/>
</div>
<style>
  .search1 {
    display: none;
  }
</style>