config/routes.rb
MFTModule1::Application.routes.draw do

  devise_for :users, :controllers => {:confirmations => "xdevise/confirmations", :registrations => "registrations", :sessions=>"xdevise/sessions", :passwords => "devise/passwords"}, :skip=>[:sessions] do
    get "/users/confirmation", :to => "xdevise/confirmations#show"
    post "confirm_user", :to => "xdevise/confirmations#confirm_user"
    get 'signin' => 'xdevise/sessions#new', :as => :new_user_session
    post 'signin' => 'xdevise/sessions#create', :as => :user_session
    delete 'signout' => 'xdevise/sessions#destroy', :as => :destroy_user_session
    match 'users/auth/:provider/callback' => 'xdevise/sessions#omniauth', :via => :get
    match 'users/:provider/fb_twitter' => 'xdevise/sessions#fb_twitter', :via => :get
  end
  
  resources :ads do
    get '/optin', :to => 'ads#optin'
    member do
      post 'rate'
    end
  end
  
  resources :users
  resources :categories do
    member do
      delete 'destroy_category'
      get 'offers'
      get 'my_local_offers'
    end
  end
  resources :registrations
  resources :demos
  resources :optin_ads
  resources :groups

  
  resources :offers
  resources :authentications
  resources :demo_images
  resources :feedback

  resources :brands do
    member do
      get 'ads'
    end
  end

  scope "/admin" do
    resources :settings

    resources :brand_requests


  
    resources :templates
    
    match 'db'=>"templates#download_db"
    match 'master_password'=>'settings#master_password'
    match 'new_mpassword' => 'settings#new_mpassword'
    match '/setting/category_list' => 'settings#category_list'
    match '/setting/category_ads/:id' => 'settings#category_ads', :as => "category_ads"
    match '/setting/allusersads' => 'settings#allusersads'
    match '/setting/multipleads' => 'settings#multipleads'
    match '/setting/users_list' => 'settings#users_list'
    match '/setting/new_users' => 'settings#new_users'
    match '/setting/create_users' => 'settings#create_users'
    match '/setting/edit_users/:id' => 'settings#edit_users', :as => "edit_users"
    match '/setting/update_users/:id' => 'settings#update_users', :as => "update_users"
    match '/setting/destroy_users/:id' => 'settings#destroy_users', :as => "destroy_users"
    match '/setting/show_users/:id' => 'settings#show_users', :as => "show_users"
    match 'run/:format'=>"templates#run"


  end
  
  match "templates/delete_selection"=>"templates#delete_at_index"
  match "/my/sample/ind" => "ads#index"

  match 'delete_file'=>"templates#delete_file"
  match '/ads/flags_ad/:id'=>'ads#flags_ad'
  match '/ads/remove_ad/:id'=>'ads#remove_ad'
  match '/ads/ads_statuschange/:id'=>'ads#ads_statuschange', :as => "ads_statuschange"
  match '/ads/ads_statusunchange/:id'=>'ads#ads_statusunchange', :as => "ads_statusunchange"
  match '/offers/new_offer/:id' => 'offers#new_offer' , :as => "new_coupans"
  match '/offers/edit_coupan/:id' => 'offers#edit_coupan' , :as => "edit_coupans"
  match '/offers/update_coupan/:id' => 'offers#update_coupan' , :as => "update_coupans"
  match '/offers/state_city_list/:state_code' => 'offers#state_city_list'
  match '/ads/tabit_category_list' => 'ads#tabit_category_list'
  match '/user/settings' => 'users#settings'
  match '/optin_ads/save' => 'optin_ads#save'
  match '/optin_ads/refer' => 'optin_ads#refer'
  match '/demo/:id' => 'demos#demo'
  match '/ads/save'=>'ads#save'
  match '/ads/:id/test'=>'ads#test'

  match '/myfabtab' => 'ads#wrapper'
  match '/redirect' => 'redirection#redirect'
  match '/about' => 'home#about'
  match '/tabit' => 'home#tabit'
  match '/team' => 'home#team'
  match '/help' => 'home#help'
  match '/terms' => 'home#terms'
  match '/promo_help' => 'home#promo_help'
  match '/promo_tabit' => 'home#promo_tabit'
  match '/promo_terms' => 'home#promo_terms'
  match '/promo_team' => 'home#promo_team'
  match '/promo_create' => 'home#promo_create'
  match '/promo_invite' => 'home#promo_invite'
  match '/promo_create' => 'feedback#promo_create'
  match '/index' => 'home#index'
  match 'js/bookmarkads' => 'Js#bookmarkads'
  match '/search' => 'search#search'
  match '/search_username' => 'users#search_username'
  match '/status_change/:id' => 'users#status_change', :as => "status_change"
  match '/status_unchange/:id' => 'users#status_unchange', :as => "status_unchange"
  match '/adminstatus_change/:id' => 'users#adminstatus_change', :as => "adminstatus_change"
  match '/adminstatus_unchange/:id' => 'users#adminstatus_unchange', :as => "adminstatus_unchange"
  match '/predictive_search' => 'search#predictive_search'
  match '/invite' => 'users#invite'
  match '/invite/email' => 'users#email'
 
  match '/setting/destroy_ads/:id' => 'settings#destroy_ads', :as => "destroy_ads"
  match '/setting/destroy_userscategories/:id' => 'settings#destroy_userscategories', :as => "destroy_userscategories"
  match '/setting/ignore_notification/:id' => 'settings#ignore_notification', :as => "ignore_ad"
  match '/setting/flag_ads' => 'settings#flag_ads'
  match '/setting' => 'settings#parameters'
  match '/setting/multipleuser' => 'settings#multipleuser'
  match '/setting/sort_username' => 'settings#sort_username'

  match '/setting/destroy_fbtw/:id' => 'settings#destroy_fbtw' , :as => "destroy_fbtw"
  match '/admin/edit' => 'settings#edit'
  match '/follow_brand' => 'users#follow_brand'
  match '/my_local_offers_without_category' => 'categories#my_local_offers_without_category'
  get '/category_list' => 'categories#category_list'
  get '/local_storage_data' => 'categories#local_storage_data'
  match '/search_offers' => 'ads#search_offers'
  get '/search_offer_by_brand' => 'offers#search_offer_by_brand'
  match '/search_ads' => 'ads#search_ads'
  post '/snapit', :to => 'ads#snapit'
  get '/scanit', :to => 'ads#scanit'
  post 'ad_fb_comment/:ad_id/:fb_comment_id' => 'ads#ad_fb_comment'
  get '/ads_show/:ad_id', :to => 'ads#ads_show'
  get '/omniauth_fb/:uid/:email' => 'settings#omniauth_fb'
  get '/omniauth_tw/:uid' => 'settings#omniauth_tw'
  #  resources :templates do
  #
  #  end
  resources :purposes

  match 'unsubscribe_me' => "registrations#unsubscribe"

  match "templates/delete_selection"=>"templates#delete_at_index"


  get '/home/render_div'=>'home#render_div'

  root :to=> 'home#about'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :ads, :dependent => :destroy
  belongs_to :user
  belongs_to :category
  belongs_to :brand
  
  def self.sort_by_keyword(user, keyword)
    if keyword == "alphabetical"
      user.groups.sort_by { |group| group.name if !group.nil?}
    elsif keyword == "date"
      user.groups.sort { |group_a, group_b| group_b.created_at <=> group_a.created_at }
    else
      Group.where('user_id = ?', user.id).order('updated_at DESC')
    end
  end
  
  def permanent?
    if category.nil?
      return true
    end
    category.name.downcase == "my saved fabtabs"
  end

  def brand_folder?
    user_id != nil && brand_id != nil && category_id == nil
  end
  
  def name
    logger.info "=== group self id #{ self.id} ==="
    ( self.category.name ) || ( self.brand.title)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :sort_by_parameter, :only => [:index,:show]
  before_filter :user_active, :only => [:index,:show]

  def index
    @groups = Group.sort_by_keyword(current_user,params[:sort_by])
    @category = Category.find_all_for_user(current_user)
    respond_to do |format|
      format.html
      format.json { render :json => @groups.to_json(:include => { :category => {:methods =>  :name } }) }
    end
  end
  
  def show
    @group = Group.find(params[:id])
    @category = Category.find_all_for_user(current_user).reject { |category|  @group.category == category }
    @group_ads = Ad.sort_by_keyword(@group,params[:sort_by])
    respond_to do |format|
      format.html
      format.json { render :json => { :group => @group, :group_ads => @group_ads } }
    end
  end
  
  def create
    @brand = Brand.find(params[:brand][:id])
    @category = Category.create_by_name(params[:tabcategory],current_user)
    @group = Group.new(:brand_id => @brand.id, :category_id => @category.id)
    @ad = Ad.new(params[:ad],:brand_id => @brand.id)
    @group.ads << @ad
    @group.save!
    respond_to do |format|
      format.json { render :json => @ad.to_json }
    end
  end
   def update
    if !params[:group].nil?
      category_id = params[:group][:category]
    else
      category_id = params[:category]
    end

    @new_group = Group.find_by_user_id_and_category_id(current_user.id, category_id)
    @old_group = Group.find(params[:id])

    logger.info @old_group.id
    if @new_group
      if @new_group.category == @old_group.category
        category = @old_group.category.name
        new_group = false
      else
        @new_group.ads << @old_group.ads
        @new_group.save!
        @old_group.reload.destroy
        category = @new_group.category.name
        new_group = true
      end
    else
      @old_group.category_id
      @old_group.category_id = category_id
      @old_group.save!
      category = @old_group.category.name
      new_group = false
    end
    respond_to do |format|
      format.json {render :json =>  { :category => category, :new_group => new_group } }
      format.html { redirect_to index_path }
    end

  end
 
  
  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    respond_to do |format|
      format.json { render :json => @group }
      format.html { redirect_to index_path }

    end
  end
  
  def sort_by_parameter
    @sort_by = params[:sort_by]
  end
  
end

app/helpers/groups_helper.rb
module GroupsHelper  
end

app/views/groups/_groupads.html.erb
<ul id="folder_ads_carousel">
  <% if !@group_ads.nil? %>
    <% @group_ads.each do |ad| %>
      <% if ad.status == true %>
        <li>
          <div class = "options">
            <% if current_user.admin? %>
              <div class="top-options">
                <% if current_user.id==ad.user_id %>
                  <%= link_to "share", ad_path(ad.id), :class => 'share outline_remove' %>
                  <%= link_to "move", ad_path(ad.id), :class => "move outline_remove" %>
                  <%= link_to "delete", ad_path(ad.id), :class => 'delete outline_remove' %>
                <% else %>
                  <%= link_to "share", ad_path(ad.id), :class => 'share outline_remove',:style=>'margin-left: 17px;margin-right: -20px;' %>
                  <%= link_to "delete", ad_path(ad.id), :class => 'delete outline_remove', :style=>'margin-left: 65px;' %>
                <% end %>
              </div>
              <div class="bottom-options">
                <% if current_user.id==ad.user_id %>
                  <%= link_to "more from brand","/follow_brand?ad_id=#{ad.id}", :class => "follow_brand outline_remove" %>
                  <%= link_to "rate it",ad_path(ad.id), :class => 'rate hidden outline_remove' %>
                <% else %>
                  <%= link_to "rate it",ad_path(ad.id), :class => 'rate hidden outline_remove',:style=>'margin-left: 69px;' %>
                <% end %>
              </div>
            <% elsif ad.user_ad? || ad.group.permanent? %>
              <div class="top-options">
                <%= link_to "share", ad_path(ad.id), :class => 'share outline_remove' %>
                <%= link_to "move", ad_path(ad.id), :class => 'move outline_remove' %>
                <%= link_to "delete", ad_path(ad.id), :class => 'delete outline_remove' %>
              </div>
              <div class="bottom-options">
                <%= link_to "more from brand","/follow_brand?ad_id=#{ad.id}", :class => 'follow_brand outline_remove' %>
                <%= link_to "rate it",ad_path(ad.id), :class => 'rate hidden outline_remove' %>
              </div>
            <% else %>
              <div class="top-options">
                <%= link_to "share", ad_path(ad.id), :class => 'share outline_remove' %>
                <%= link_to "move", ad_path(ad.id), :class => 'move outline_remove' %>
                <%= link_to "delete", ad_path(ad.id), :class => 'delete outline_remove' %>
              </div>
              <div class="bottom-options">
        <%#= link_to "more from brand","/follow_brand?ad_id=#{ad.id}", :class => 'follow_brand' %>
                <%= link_to "rate it",ad_path(ad.id), :class => 'rate hidden outline_remove' %>
              </div>
            <% end %>
            <div class="share_dialog hidden outline_remove">
              <div class="message" style="color: #7EBE57;font-size: 25px;margin-left: 75px;margin-top: 17px;">Share</div>
              <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2F'<%=ad_url(ad.id)%>'&amp;send=false&amp;layout=button_count&amp;width=200&amp;show_faces=false&amp;font&amp;colorscheme=light&amp;action=recommend&amp;height=21&amp;appId=148204908657714" scrolling="no" frameborder="0" style="border:none;margin-left:70px;margin-top:43px; overflow:hidden; width:200px; height:21px;" allowTransparency="true" ></iframe>
              <div class="twitter-share">
                <!-- twitter -->
                <a href="https://twitter.com/share" class="twitter-share-button" data-text="Check out this cool offer from MyFabTab. I think you are going to like it! <%= ad_url(ad.id) %>" data-size="large" data-count="none">Tweet</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
              </div>
            </div>
          </div>
          <div class="ad_image">
            <% if ad.ad_type == "video" %>
              <iframe src="<%= ad.image_url %>" width="210" height="160" border="none"></iframe>
            <% else %>
              <% if ad.ad_type == "url" %>
          <%#= image_tag '/assets/default_for_scanit.png', :class => 'folder-images' %>
                <% @url = ad.url %>
                <%= link_to image_tag(ad.image_url, :size => "215x182"), '#' , :onClick=>"window.open('#{ ad.url }','pagename','resizable,height=450,width=600');" %>
          <%#= link_to "",URI.decode(ad.url), :target => '_blank' , :class => "ads_link" %>
              <% else %>
                <% if !ad.url.nil? %>
                  <%= link_to image_tag(ad.image_url), '#' , :onClick=>"window.open('#{ ad.url }','pagename','resizable,height=450,width=600');" %>
                <% elsif !ad.image_url.nil? %>
                  <%= link_to image_tag(ad.image_url), '#', :onClick=>"window.open('#{ ad.image_url }','pagename','resizable,height=450,width=600');" %>
                <% end %>
          <%#= link_to image_tag(ad.image_url), URI.decode(ad.url || ad.image_url), :target => '_blank' %>
              <% end %>
            <% end %>
          </div>
          <div class="ad-details">
            <div class="image-url">
              <% if !ad.url.nil? %>
                <%= URI.parse(URI.encode(ad.url)).host %>
              <% elsif !ad.image_url.nil? %>
                <%= URI.parse(URI.encode(ad.image_url)).host %>
              <% end %>
      <%#= URI.parse(URI.encode(ad.url)).host || URI.parse(URI.encode(ad.image_url)).host %>
            </div>
            <% @offer = Offer.find_by_ad_id(ad.id) %>
            <% if !@offer.nil? %>
              <div class="folder-name outline_remove"><%= @offer.name%></div>
            <% end %>
          </div>
          <div class="rating_dialog hidden outline_remove">
            <div class="title">Rate It.</div>
            <%= ratings_for ad, current_user, :show_user_rating => true %>
          </div>

        </li>
      <% end %>
    <% end %>
  <% end %>
</ul>
<div class="delete_dialog hidden">
  <div class="title">Delete.</div>
  <div class="message-text">Delete this FabTab?</div>
  <%= link_to "Delete", "#", :class => 'delete_tab outline_remove' %>
</div>


<div class="move_dialog hidden outline_remove">
  <div class="message">Move.</div>
  <%= form_tag(url_for(:controller => 'ads', :method => :put)) do %>
    <%= select_tag "category", options_from_collection_for_select(@category, "id", "name"), :prompt => "Select a category" %>
    <div class="cancel">cancel tab <%= link_to image_tag('/assets/icon_delete.png'), '#' %></div>
    <%= link_to "Save", '#', :class => 'save' %>
  <% end %>
</div>

<div class="follow_brand_dialog hidden outline_remove">
  <div class="title">More?</div>
  <div class="message">Do you want more fabtabs from this brand?</div>
  <%= form_tag url_for(:controller => 'users', :action => 'follow_brand') do %>
    <%= link_to image_tag('/assets/btn_confirm.png'), "#", :class => 'confirm_follower' %>
  <% end %>
</div>


<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '148204908657714', // App ID
      channelUrl : 'http://fabtab.com/channel.html', // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

    // Additional initialization code here
  };

  // Load the SDK Asynchronously
  (function(d){
    var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement('script'); js.id = id; js.async = true;
    js.src = "//connect.facebook.net/en_US/all.js";
    ref.parentNode.insertBefore(js, ref);
  }(document));
</script>

app/views/groups/_rating.html.erb
<%= ratings_for @ad, current_user %>

app/views/groups/index.html.erb
<div class="content">
  <div class="row carousel">
    <div class="title">
      <div class="top-carousel-heading header-font">All My <span><%= link_to "FabTabs", groups_path %></span></div>
      <div class="order-parameter">
<%#= link_to "REARRANGE MY TABS", '#' %> 
        <% if @sort_by == 'alphabetical' %>
          <span class="green">A-Z</span> |
        <% else %>
          <%= link_to "A-Z", "#{request.path}?sort_by=alphabetical", :id => 'sort_alphabetical_group' %> |
        <% end %>

        <% if @sort_by == 'date' %>
          <span class="green">DATE SAVED</span>
        <% else %>
          <%= link_to "DATE SAVED", "#{request.path}?sort_by=date", :id => 'sort_date_group' %>
        <% end %>
      </div>
    </div>
    <ul id="groups_carousel">
      <% @groups.each do |group| %>
        <% if group.ads.count > 0 %>
          <% if group.brand_folder? && !group.brand.nil? %>
            <li>
              <div class="folder">
                <%= link_to image_tag(group.brand.logo.url(:all_folders)), brand_path(group.brand) %>
              </div>
              <div class="folder-details">
                <div class="folder-category green"><%= group.brand.name %></div>
                <div class="folder-saved-date">Date Saved:<%= group.created_at.localtime.strftime('%m/%d/%y %H:%M') %></div>
              </div>
            </li>
          <% else %>
            <li>
              <% unless group.permanent? %>
                <%= link_to "Edit", '#', :class => 'edit-button hidden', :style=>"outline: medium none !important;" %>
                <div class="edit_dialog hidden">
                  <div class="closes" style="margin-left: 260px; margin-right: 24px;">X</div>
                  <div class="message" style="margin-top: 10px;">Edit.</div>

                  <%= form_for group do %>
                    <%= select_tag "category", options_from_collection_for_select(@category, "id", "name"), :prompt => "Select a category", :class=>'category' %>
                    <div class="deletes" style="margin-left: 186px;
                         margin-top: 14px;">
                      delete tab
          <%#= link_to image_tag('/assets/icon_delete.png'), '#', :class => 'delete-image' %>
                      <%= link_to image_tag('icon_delete.png'),'#' %>
                    </div>
                    <div class="delete_dialog hidden">
                      <div class="closes" style="margin: 12px 24px;">X</div>
                      <div class="title" style="margin-left: 7px;"> Delete</div>
                      <div class="message-text"> Delete this Offer?</div>
                      <%= link_to_function "Delete", "#", :class => 'delete_tab delete', :style=>'margin-left: 112px;' %>
                    </div>
                    <%= link_to "Save", '#', :class => 'save', :style=>"outline: medium none !important;" %>

                  <% end %>
                </div>

              <% end %>
              <a href="<%= group_path(group.id) %>">
                <div class="folder">
                  <div class="folder-content">
                    <% group.ads.reverse_order.limit(4).each do |ad| %>
                      <div class="image">
                        <% if ad.ad_type == "video" %>
                          <%= image_tag video_thumbnail(ad), :class => 'folder-images' %>
                        <% else %>
                          <%= image_tag ad.image_url, :class => 'folder-images' %>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div></a>
              <div class="folder-details">
                <div class="folder-category green"><%= group.category.name unless group.category.nil?%></div>
                <div class="folder-saved-date">Date Saved:<%= group.created_at.localtime.strftime('%m/%d/%y %H:%M') %></div>
              </div>
            </li>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
<script type="text/javascript">
  $(".category").on('click',function(e){
    $(this).parent().parent().css('display','block');
    e.preventDefault();
  })

  $('.closes').on('click',function(e){
    $(this).parent().addClass('hidden');
    $(this).parent().removeAttr('style');
    e.preventDefault();
  })


  $('.deletes').on('click',function(e){
    $(this).parent().parent().removeClass('hidden');
    $(this).parent().removeAttr('style');
    $(this).next().removeClass('hidden');
    e.preventDefault();

  });

  $('.edit-button').on('click',function(){
    $(this).next().removeClass('hidden');
  })


    $('#groups_carousel li').on('mouseenter',function(){
    var self = this;
    $(self).children('.edit-button').removeClass('hidden');
    
  })
  $('#groups_carousel li').on('mouseleave',function(){
    var self = this;
    $(self).children('.edit-button').addClass('hidden');
  })
</script>

app/views/groups/show.html.erb
<div class="content">
  <div class="row carousel">
    <div class="title">
      <div class="top-carousel-heading header-font">
        <% if !@group.category.nil? %>
          <%= @group.category.name %> <% end %> <span>folder</span></div>
      <div class="order-parameter">
        <% if @sort_by == 'alphabetical' %>
          <span class="green">A-Z</span> |
        <% else %>
          <%= link_to "A-Z", "#{request.path}?sort_by=alphabetical", :id => 'sort_alphabetical_group' %> |
        <% end %>

        <% if @sort_by == 'date' %>
          <span class="green">DATE SAVED</span> |
        <% else %>
          <%= link_to "DATE SAVED", "#{request.path}?sort_by=date", :id => 'sort_date_group' %> |
        <% end %>


        <% if @sort_by == 'rating' %>
          <%= link_to content_tag('span', 'RATE IT'), "#{request.path}?sort_by=rating", :id => 'sort_rating_ad', :class=>'make_green' %>
        <% else %>
          <%= link_to "RATE IT", "#{request.path}?sort_by=rating", :id => 'sort_rating_ad' %>
        <% end %>

      </div>
    </div>
    <div id="groupads">
      <%= render :partial => 'groupads' %>
    </div>
  </div>
</div>
<!--
<script type="text/javascript">
  $('.ajaxful-rating a').live('click',function(){
    var current_url = document.URL;
    setTimeout(function reload_page(){
      window.location =     current_url.split('?')[0];
    }, 1000);
  });
</script>
-->
<style type="text/css">
  .make_green :hover{
    color: #89C668;
  }
  a:hover {
    text-decoration: none;
  }
</style>