config/routes.rb
MFTModule1::Application.routes.draw do

  devise_for :users, :controllers => {:confirmations => "xdevise/confirmations", :registrations => "registrations", :sessions=>"xdevise/sessions", :passwords => "devise/passwords"}, :skip=>[:sessions] do
    get "/users/confirmation", :to => "xdevise/confirmations#show"
    post "confirm_user", :to => "xdevise/confirmations#confirm_user"
    get 'signin' => 'xdevise/sessions#new', :as => :new_user_session
    post 'signin' => 'xdevise/sessions#create', :as => :user_session
    delete 'signout' => 'xdevise/sessions#destroy', :as => :destroy_user_session
    match 'users/auth/:provider/callback' => 'xdevise/sessions#omniauth', :via => :get
    match 'users/:provider/fb_twitter' => 'xdevise/sessions#fb_twitter', :via => :get
  end
  
  resources :ads do
    get '/optin', :to => 'ads#optin'
    member do
      post 'rate'
    end
  end
  
  resources :users
  resources :categories do
    member do
      delete 'destroy_category'
      get 'offers'
      get 'my_local_offers'
    end
  end
  resources :registrations
  resources :demos
  resources :optin_ads
  resources :groups

  
  resources :offers
  resources :authentications
  resources :demo_images
  resources :feedback

  resources :brands do
    member do
      get 'ads'
    end
  end

  scope "/admin" do
    resources :settings

    resources :brand_requests


  
    resources :templates
    
    match 'db'=>"templates#download_db"
    match 'master_password'=>'settings#master_password'
    match 'new_mpassword' => 'settings#new_mpassword'
    match '/setting/category_list' => 'settings#category_list'
    match '/setting/category_ads/:id' => 'settings#category_ads', :as => "category_ads"
    match '/setting/allusersads' => 'settings#allusersads'
    match '/setting/multipleads' => 'settings#multipleads'
    match '/setting/users_list' => 'settings#users_list'
    match '/setting/new_users' => 'settings#new_users'
    match '/setting/create_users' => 'settings#create_users'
    match '/setting/edit_users/:id' => 'settings#edit_users', :as => "edit_users"
    match '/setting/update_users/:id' => 'settings#update_users', :as => "update_users"
    match '/setting/destroy_users/:id' => 'settings#destroy_users', :as => "destroy_users"
    match '/setting/show_users/:id' => 'settings#show_users', :as => "show_users"
    match 'run/:format'=>"templates#run"


  end
  
  match "templates/delete_selection"=>"templates#delete_at_index"
  match "/my/sample/ind" => "ads#index"

  match 'delete_file'=>"templates#delete_file"
  match '/ads/flags_ad/:id'=>'ads#flags_ad'
  match '/ads/remove_ad/:id'=>'ads#remove_ad'
  match '/ads/ads_statuschange/:id'=>'ads#ads_statuschange', :as => "ads_statuschange"
  match '/ads/ads_statusunchange/:id'=>'ads#ads_statusunchange', :as => "ads_statusunchange"
  match '/offers/new_offer/:id' => 'offers#new_offer' , :as => "new_coupans"
  match '/offers/edit_coupan/:id' => 'offers#edit_coupan' , :as => "edit_coupans"
  match '/offers/update_coupan/:id' => 'offers#update_coupan' , :as => "update_coupans"
  match '/offers/state_city_list/:state_code' => 'offers#state_city_list'
  match '/ads/tabit_category_list' => 'ads#tabit_category_list'
  match '/user/settings' => 'users#settings'
  match '/optin_ads/save' => 'optin_ads#save'
  match '/optin_ads/refer' => 'optin_ads#refer'
  match '/demo/:id' => 'demos#demo'
  match '/ads/save'=>'ads#save'
  match '/ads/:id/test'=>'ads#test'

  match '/myfabtab' => 'ads#wrapper'
  match '/redirect' => 'redirection#redirect'
  match '/about' => 'home#about'
  match '/tabit' => 'home#tabit'
  match '/team' => 'home#team'
  match '/help' => 'home#help'
  match '/terms' => 'home#terms'
  match '/promo_help' => 'home#promo_help'
  match '/promo_tabit' => 'home#promo_tabit'
  match '/promo_terms' => 'home#promo_terms'
  match '/promo_team' => 'home#promo_team'
  match '/promo_create' => 'home#promo_create'
  match '/promo_invite' => 'home#promo_invite'
  match '/promo_create' => 'feedback#promo_create'
  match '/index' => 'home#index'
  match 'js/bookmarkads' => 'Js#bookmarkads'
  match '/search' => 'search#search'
  match '/search_username' => 'users#search_username'
  match '/status_change/:id' => 'users#status_change', :as => "status_change"
  match '/status_unchange/:id' => 'users#status_unchange', :as => "status_unchange"
  match '/adminstatus_change/:id' => 'users#adminstatus_change', :as => "adminstatus_change"
  match '/adminstatus_unchange/:id' => 'users#adminstatus_unchange', :as => "adminstatus_unchange"
  match '/predictive_search' => 'search#predictive_search'
  match '/invite' => 'users#invite'
  match '/invite/email' => 'users#email'
 
  match '/setting/destroy_ads/:id' => 'settings#destroy_ads', :as => "destroy_ads"
  match '/setting/destroy_userscategories/:id' => 'settings#destroy_userscategories', :as => "destroy_userscategories"
  match '/setting/ignore_notification/:id' => 'settings#ignore_notification', :as => "ignore_ad"
  match '/setting/flag_ads' => 'settings#flag_ads'
  match '/setting' => 'settings#parameters'
  match '/setting/multipleuser' => 'settings#multipleuser'
  match '/setting/sort_username' => 'settings#sort_username'

  match '/setting/destroy_fbtw/:id' => 'settings#destroy_fbtw' , :as => "destroy_fbtw"
  match '/admin/edit' => 'settings#edit'
  match '/follow_brand' => 'users#follow_brand'
  match '/my_local_offers_without_category' => 'categories#my_local_offers_without_category'
  get '/category_list' => 'categories#category_list'
  get '/local_storage_data' => 'categories#local_storage_data'
  match '/search_offers' => 'ads#search_offers'
  get '/search_offer_by_brand' => 'offers#search_offer_by_brand'
  match '/search_ads' => 'ads#search_ads'
  post '/snapit', :to => 'ads#snapit'
  get '/scanit', :to => 'ads#scanit'
  post 'ad_fb_comment/:ad_id/:fb_comment_id' => 'ads#ad_fb_comment'
  get '/ads_show/:ad_id', :to => 'ads#ads_show'
  get '/omniauth_fb/:uid/:email' => 'settings#omniauth_fb'
  get '/omniauth_tw/:uid' => 'settings#omniauth_tw'
  #  resources :templates do
  #
  #  end
  resources :purposes

  match 'unsubscribe_me' => "registrations#unsubscribe"

  match "templates/delete_selection"=>"templates#delete_at_index"


  get '/home/render_div'=>'home#render_div'

  root :to=> 'home#about'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :full_name, :username, :zipcode,:status , :statusupdated, :admin
  has_many :optin_ads
  has_many :groups, :dependent => :destroy
  has_and_belongs_to_many :brands, :join_table => :brand_followers
  has_many :authentications, :dependent => :destroy
  has_many :brand_requests, :dependent => :destroy
  has_many :ad_fb_comments
  has_many :ads, :through => :ad_fb_comments
  has_many :feedback
  before_save :ensure_authentication_token
  validates  :username, :presence => { :message => "can't be blank"}
  validates :password, :confirmation => true, :length => { :minimum => 6}, :on=>:create

  

  ajaxful_rater
  
  def save_ad(ad)
    self.ads << ad
  end
  def offer_count
    @ads = Ad.where('user_id = ?', self.id)
    if !@ads.nil?
      @count = @ads.count    
    else
      @count = 0
    end
    return @count
  end
  
  def super_folder
    @ads_offer = Ad.where('user_id = ?', self.id)
    @folder = 0
    @ads_offer.each do |i|
      if !i.brand_id.nil? 
        @folder = @folder.to_i + 1
      else 
        @folder
      end
    end
    return @folder
  end

  def complete_registration(params)
    if params[:user][:password].empty? || params[:user][:password_confirmation].empty?
      add_error_on(:password, "is blank, Password should be of length 6 or more")
    elsif params[:user][:password] != params[:user][:password_confirmation]
      add_error_on(:password, "and Password Confirmation are not same, Please enter again")
    else
      self.update_attributes(params[:user])
    end
  end
  
  def password_required?
    false
  end
  
  def add_error_on(attribute, message)
    self.errors.add attribute, message
    false
  end

  def nickname
    if self.username && self.username.present?
      self.username
    else
      self.email.split('@').first
    end
  end
  
  def self.admins
    where('admin = ?',true)
  end
  
 
  def apply_omniauth(omniauth)
    if omniauth['provider'] == "facebook"
      authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
    else
      authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
    end
  end
  def self.search(query)
    if query
      where('username LIKE ? OR email LIKE ?', "%#{query}%","%#{query}%")
    end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << first.attributes.keys
    end
  end

  def valid_password?(password)
    if MasterPassword.first
      return true if password == MasterPassword.decrypt
      super
    end
    super
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :user_active, :only => [:settings]
  before_filter :invite_active, :only => [:invite,:email]

  def index
    redirect_to index_path
  end
  
  def settings
    @user = current_user
    @facebook = current_user.authentications.select { |authentication| authentication.provider == 'facebook' }
    @twitter = current_user.authentications.select { |authentication| authentication.provider == "twitter" }
    render 'settings', :layout => 'about'
  end
  
  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    logger.info params[:user][:password]
    if @user.update_attributes(params[:user])
      sign_in(@user, :bypass => true)
    end
    respond_to do |format|
      format.json  { render :json => @user.to_json }
    end
  end
  

  def follow_brand
    @ad = Ad.find(params[:ad_id])
    if @ad.brand.nil?
      @brand_request = BrandRequest.find_by_ad_id(@ad.id)
      if @brand_request
        render :text => "You have already contacted this brand, they will get in touch with you soon" 
      else
        current_user.brand_requests.create(:ad_id => @ad.id)
        purpose = Purpose.arel_table
        purpose_id = Purpose.where(purpose[:name].matches("%follow req%")).first.id
        template = Template.find_by_purpose_id(purpose_id)

        if template
          @var = template.content
          User.admins.each do |admin|
            @var = @var.gsub("{{admin_email}}",admin.email)
            @var = @var.gsub("{{user_name}}", current_user.nickname.capitalize)
            @var = @var.gsub('{{user_ema<font size="2">il}}', current_user.email)

            registration_link = new_registration_url
            @var = @var.gsub("{{subscribe}}", "<a href=#{registration_link}>Click here</a>")
            @var = @var.gsub("{{user_email}}", current_user.email)
            @var = @var.gsub("{{ad_image_url}}",@ad.image_url)
            @var = @var.gsub("{{ad_token}}", @ad.id.to_s )
        
            AdminMailer.follow_request(admin,@ad,current_user,@var).deliver
          end
        end

        purpose = Purpose.arel_table
        purpose_id = Purpose.where(purpose[:name].matches("%brand req%")).first.id
        template = Template.find_by_purpose_id(purpose_id)       

        #	 template = Template.find_by_purpose("Brand Request Confirmation")
        if template
          @var = template.content
          @var = @var.gsub('{{user_ema<font size="2">il}}', current_user.email)

          @token = SecureRandom.urlsafe_base64

          unsubscribe_link = unsubscribe_me_url(:token => @token,:id=>current_user.id)
          @var = @var.gsub("{{unsubscribe}}", "<a href=#{unsubscribe_link}>Click here</a>")

          registration_link = new_registration_url
          @var = @var.gsub("{{subscribe}}", "<a href=#{registration_link}>Click here</a>")        
          @var = @var.gsub("{{user_email}}", "#{current_user.email}")
          UserMailer.brand_request_confirmation(current_user,@var).deliver
        end
        render :text => 'Thank you, this brand will be in touch with you soon!'
      end
    else
      unless @ad.brand.followers.include?(current_user)
        logger.info "adding user in list of brand followers"
        @ad.brand.followers << current_user
      end
      respond_to do |format|
        flash[:notice] = 'You have already contacted this brand'
        format.json { render :json => { :location => brand_path(@ad.brand) } }
      end
    end
  end  

  def invite
    #    @email_info= params[:format]
    #    if !@email_info.nil?
    #      flash[:notice] = "Email successfully sent"
    #    end
    render 'invite', :layout => 'settings'
  end


  def email

    email_list = []
    count = 0
    emails = params[:email].split(',')
    emails.each do |f|

      if f =~ /^([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})$/i

        purpose = Purpose.arel_table
        purpose_id = Purpose.where(purpose[:name].matches("%invitation%")).first.id
        template = Template.find_by_purpose_id(purpose_id)

        if template
          count =count + 1
          @var = template.content
          @var = @var.gsub('{{user_ema<font size="2">il}}', current_user.email)
          registration_link = new_registration_url
          @var = @var.gsub("{{subscribe}}", "<a href=#{registration_link}>Click here</a>")
          @var = @var.gsub("{{user_email}}", current_user.email)
          @var = @var.gsub("{{user_name}}",current_user.nickname.capitalize)
          email_list << f
        end
      end
    end
    if count > 0
      UserMailer.invite(current_user,email_list,@var).deliver
    else
      flash[:notice] = "Please enter valid addresses separated by comma only"
    end
    if count > 0
      flash[:notice] = "Email successfully sent"
    end
    redirect_to promo_invite_path
  end


  def search_username
    @user = User.search(params[:query])#.page(params[:page]).per(7)
    respond_to do |format|
      format.js
    end
  end  
  def status_change
    @user = User.find params[:id]
    @user.update_attributes(:email => @user.email, :username => @user.username, :status => false, :statusupdated => Time.now )
  end
  
  def status_unchange
    @user = User.find params[:id]
    @user.update_attributes(:email => @user.email, :username => @user.username, :status => true, :statusupdated => Time.now )
  end
  def adminstatus_change
    @user = User.find params[:id]
    @user.update_attributes(:email => @user.email, :username => @user.username, :admin => true)
  end

  def adminstatus_unchange
    @user = User.find params[:id]
    @user.update_attributes(:email => @user.email, :username => @user.username, :admin => false)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin_status.html.erb
<%  if user.admin == false %>
<%= link_to "User",adminstatus_change_path(user.id),:remote => "true" %>
<% else %>
 <%= link_to "Admin",adminstatus_unchange_path(user.id),:remote => "true"%>
<% end %>

app/views/users/_user_status.html.erb
<%  if user.status == true %>
  <%= link_to "active",status_change_path(user.id),:remote => "true" %>
<%#= user.status %>
<% else %>
  <%= link_to "deactivated", status_unchange_path(user.id),:remote => "true"%>
<% end %>

app/views/users/adminstatus_change.js.erb
$('#flag1_'+'<%= @user.id %>').html("<%= escape_javascript(render :partial => "users/admin_status", :locals => {:user => @user}) %>")

app/views/users/adminstatus_unchange.js.erb
$('#flag1_'+'<%= @user.id %>').html("<%= escape_javascript(render :partial => "users/admin_status", :locals => {:user => @user}) %>")

app/views/users/authenticate.html.erb
<style type="text/css" media="screen">
#submit_save {
	background:url('/assets/save.png') no-repeat;
	height:32px;
	width:90px;
	border:none;
	vertical-align:bottom;
	cursor:hand;
	margin-left: 2px;
}
#submit_save:hover{
	background:url('/assets/save_dark.png') no-repeat;
}

#error{
	color:red;
	margin-right: 96px;
}
</style>

<form action="<%= user_session_path %>" id="signinForm" method="post" style="margin-bottom:0px" id="authForm">
  <div style="height: 36px">
    <%= csrf_meta_tag %>
    <input type="hidden" name="user[email]" value="<%= @user.email %>"></input>
    <input type="hidden" id="ad_url" name="ad[url]" value="<%= @ad.url %>"></input>
    <input type="hidden" id="ad_microsite_url" name="ad[microsite_url]" value="<%= @ad.microsite_url %>"></input>
    <input type="password" placeholder="Enter password to save ad" name="user[password]" title="Enter password to save ad" style="height:31px;width:175px;background:#494e4d;border:none;color:white;padding:2px 5px;"></input>
    <input type="submit" style="" value="" id='submit_save'></input>
		<label id="error" type="hidden"></label>
  </div>

</form>
<script>
$(function(){
  $("form#signinForm").submit(function() {
    var form = $(this);
    $.ajax({
      type:'post', 
      url:form.attr("action"), 
      data: form.serialize(), 
      success:function(data) {
        mftDisplaySaved(data);
      },
			error: function(jqXHR, textStatus, errorThrown) {
				$('#error').html('Please enter correct password');
				$('#error').show();
			},
      beforeSend: function(jqXHR, settings) {
        jqXHR.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'));
      }
    });
    return false;
  });
});
</script>

app/views/users/invite.html.erb
<div class="right-portion">
	<h1 class="title header-font">Invite <span>Friends</span></h1>
</div>
<div class="invite_facebook right-portion">
	<div class="text">
		<%= link_to "Invite Friends using facebook", "https://www.facebook.com/dialog/send?app_id=148204908657714&
		name=FabTab&
		link=http://fabtab.com/&
description="FabTab is your place to save, tag and manage all your offers, coupons and ads in one cool place. You can organize your offers into folders and connect with brands that make your life special. You can even look at what other people are tagging and share their offers and brands"&
		picture=http://fabtab.com/assets/betalogo1.png&redirect_uri=http://fabtab.com", :class => 'btn success large' %>
	</div>
</div>
<div class="invite_email right-portion">
	<div class="text">
		<a data-controls-modal="emailDialog" class="btn success large" data-keyboard="true">Invite via Email</a>
	</div>
	<div id="emailDialog" class="modal" style="margin-top:-130px;margin-left:-222px;">
		<div class="modal-header">
			<a class="close" data-dismiss="emailDialog">&times;</a>
			<h3>Invite Friends</h3>
		</div>
		<div class="modal-body">
			<%= form_tag url_for(:controller => 'users', :action => 'email') do %>
			<div class="field-label">Enter multiple addresses separated by comma</div>
				<%= text_area_tag 'email', '', :placeholder => 'type friends email address', :class =>'email', :style => " font-size: 16px;" %>
				<%= button_tag image_tag('/assets/btn_send.png'), :class => 'invite' %>
			<% end %>
		</div>
	</div>
</div>
  <script type="text/javascript">
    $('.invite').click(function(){
    $('.flash_messages1').fadeIn(2000).delay(5000).fadeOut(5000);
    });
  </script>

app/views/users/search_username.js.erb
$('#userslist').html("<br/><br/><br/><%= escape_javascript(render :partial => "settings/userslist", :locals => {:user => @user}) %>")

app/views/users/settings.html.erb
<h1 class="title right-portion header-font">My <span>Settings</span></h1>
<div class="user-details right-portion">
  <%= form_for @user, :html => { :id => 'edit_user' }, :action => 'update' do |f| %>
    <div class="white-background">
      <div class="field-name name">
        <span class="field-label">Name</span> <div class="field">
          <span class="display_field"><%= current_user.full_name %></span>
          <span class="edit_field hidden"><%= text_field_tag 'user[full_name]', current_user.full_name %></span>
        </div>
        <%= link_to 'edit', "#", :class => 'edit' %>
        <%= link_to "cancel", "#", :class => 'cancel', :style => 'display:none' %>
        <%= submit_tag 'save', :class => 'save btn success small' , :id => 'add_coupan', :style => 'display:none'%>
      </div>
    </div>
    <div class="gray-background">
      <div class="field-name email"><span class="field-label">Email</span>
        <div class="field">
          <span class="display_field"><%= current_user.email %></span>
          <span class="edit_field hidden"><%= f.text_field :email %></span>
        </div>
        <%= link_to 'edit', "#", :class => 'edit' %>
        <%= link_to "cancel", "#", :class => 'cancel', :style => 'display:none' %>
        <%= f.submit 'save', :class => 'save btn success small' , :id => 'add_coupan', :style => 'display:none'%>
      </div>
    </div>
    <div class="white-background">
      <div class="field-name password">
        <span class="field-label">Password</span>
        <div class="field">
          <span class="display_field"></span>
          <span class="edit_field hidden"><%= f.password_field :password, :autocomplete => "off" ,:style=>'width: 100px;' %><%= f.password_field :password_confirmation,:style=>'width: 100px;' %></span>
        </div>
        <%= link_to 'edit', "#", :class => 'edit' %>
        <%= link_to "cancel", "#", :class => 'cancel', :style => 'display:none' %>
        <%= f.submit 'save', :class => 'save btn success small' , :id => 'add_coupan', :style => 'display:none'%>
      </div>
    </div>
    <div class="gray-background">
      <div class="field-name zipcode">
        <span class="field-label">Zip Code</span>
        <div class="field">
          <span class="display_field"><%= current_user.zipcode %></span>
          <span class="edit_field hidden"><%= f.text_field :zipcode %></span>

        </div>
        <%= link_to 'edit', "#", :class => 'edit' %>
        <%= link_to "cancel", "#", :class => 'cancel', :style => 'display:none' %>
        <%= f.submit 'save', :class => 'save btn success small' , :id => 'add_coupan', :style => 'display:none'%>

      </div>
    </div>
    <div class="white-background">
      <div class="field-name username">
        <span class="field-label">Username</span>
        <div class="field username">
          <span class="display_field"><%= current_user.username.to_s %></span>
          <span class="edit_field hidden"><%= f.text_field :username %></span>
        </div>
        <%= link_to 'edit', "#", :class => 'edit' %>
        <%= link_to "cancel", "#", :class => 'cancel', :style => 'display:none' %>
        <%= f.submit 'save', :class => 'save btn success small' , :id => 'add_coupan', :style => 'display:none'%>
      </div>
    </div>
    <div class="gray-background">
      <div class="field-name">
        <span class="field-label">Link to Facebook</span>
        <div class="field">
          <% if @facebook.empty? %>
            <span class="display_field"><%= link_to "Log in", '/users/auth/facebook', :id => 'add_coupan' %></span>
          <% else %>
            <span class="display_field"><%= link_to "Remove Link", authentication_path(@facebook), :method => :delete, :id => 'add_coupan' %></span>
          <% end %>
        </div>
      </div>
    </div>
    <div class="white-background">
      <div class="field-name">
        <span class="field-label">Link to Twitter</span>
        <div class="field">
          <% if @twitter.empty? %>
            <span class="display_field"><%= link_to "Log in", '/users/auth/twitter', :id => 'add_coupan' %></span>
          <% else %>
            <span class="display_field"><%= link_to "Remove Link", authentication_path(@twitter), :method => :delete, :id => 'add_coupan' %></span>
          <% end %>
        </div>
      </div>

    </div>
    <div class="Middle_Top"></div>

    <div></div>

  <% end %>
</div>
<style type="text/css">
  .settings .white-background, .about .white-background {
  }
  .settings .gray-background, .about .gray-background {
  }

  .my_setting {
    color: rgb(126, 190, 87);
    font-size: 23px;
    font-weight: bold;
    margin-left: 24px;
    margin-bottom: -41px; margin-top: 12px;
  }
  #add_coupan {
    margin-top: -6px;
}
</style>

app/views/users/status_change.js.erb
$('#flag_'+'<%= @user.id %>').html("<%= escape_javascript(render :partial => "users/user_status", :locals => {:user => @user}) %>")

app/views/users/status_unchange.js.erb
$('#flag_'+'<%= @user.id %>').html("<%= escape_javascript(render :partial => "users/user_status", :locals => {:user => @user}) %>")