config/routes.rb
MFTModule1::Application.routes.draw do

  devise_for :users, :controllers => {:confirmations => "xdevise/confirmations", :registrations => "registrations", :sessions=>"xdevise/sessions", :passwords => "devise/passwords"}, :skip=>[:sessions] do
    get "/users/confirmation", :to => "xdevise/confirmations#show"
    post "confirm_user", :to => "xdevise/confirmations#confirm_user"
    get 'signin' => 'xdevise/sessions#new', :as => :new_user_session
    post 'signin' => 'xdevise/sessions#create', :as => :user_session
    delete 'signout' => 'xdevise/sessions#destroy', :as => :destroy_user_session
    match 'users/auth/:provider/callback' => 'xdevise/sessions#omniauth', :via => :get
    match 'users/:provider/fb_twitter' => 'xdevise/sessions#fb_twitter', :via => :get
  end
  
  resources :ads do
    get '/optin', :to => 'ads#optin'
    member do
      post 'rate'
    end
  end
  
  resources :users
  resources :categories do
    member do
      delete 'destroy_category'
      get 'offers'
      get 'my_local_offers'
    end
  end
  resources :registrations
  resources :demos
  resources :optin_ads
  resources :groups

  
  resources :offers
  resources :authentications
  resources :demo_images
  resources :feedback

  resources :brands do
    member do
      get 'ads'
    end
  end

  scope "/admin" do
    resources :settings

    resources :brand_requests


  
    resources :templates
    
    match 'db'=>"templates#download_db"
    match 'master_password'=>'settings#master_password'
    match 'new_mpassword' => 'settings#new_mpassword'
    match '/setting/category_list' => 'settings#category_list'
    match '/setting/category_ads/:id' => 'settings#category_ads', :as => "category_ads"
    match '/setting/allusersads' => 'settings#allusersads'
    match '/setting/multipleads' => 'settings#multipleads'
    match '/setting/users_list' => 'settings#users_list'
    match '/setting/new_users' => 'settings#new_users'
    match '/setting/create_users' => 'settings#create_users'
    match '/setting/edit_users/:id' => 'settings#edit_users', :as => "edit_users"
    match '/setting/update_users/:id' => 'settings#update_users', :as => "update_users"
    match '/setting/destroy_users/:id' => 'settings#destroy_users', :as => "destroy_users"
    match '/setting/show_users/:id' => 'settings#show_users', :as => "show_users"
    match 'run/:format'=>"templates#run"


  end
  
  match "templates/delete_selection"=>"templates#delete_at_index"
  match "/my/sample/ind" => "ads#index"

  match 'delete_file'=>"templates#delete_file"
  match '/ads/flags_ad/:id'=>'ads#flags_ad'
  match '/ads/remove_ad/:id'=>'ads#remove_ad'
  match '/ads/ads_statuschange/:id'=>'ads#ads_statuschange', :as => "ads_statuschange"
  match '/ads/ads_statusunchange/:id'=>'ads#ads_statusunchange', :as => "ads_statusunchange"
  match '/offers/new_offer/:id' => 'offers#new_offer' , :as => "new_coupans"
  match '/offers/edit_coupan/:id' => 'offers#edit_coupan' , :as => "edit_coupans"
  match '/offers/update_coupan/:id' => 'offers#update_coupan' , :as => "update_coupans"
  match '/offers/state_city_list/:state_code' => 'offers#state_city_list'
  match '/ads/tabit_category_list' => 'ads#tabit_category_list'
  match '/user/settings' => 'users#settings'
  match '/optin_ads/save' => 'optin_ads#save'
  match '/optin_ads/refer' => 'optin_ads#refer'
  match '/demo/:id' => 'demos#demo'
  match '/ads/save'=>'ads#save'
  match '/ads/:id/test'=>'ads#test'

  match '/myfabtab' => 'ads#wrapper'
  match '/redirect' => 'redirection#redirect'
  match '/about' => 'home#about'
  match '/tabit' => 'home#tabit'
  match '/team' => 'home#team'
  match '/help' => 'home#help'
  match '/terms' => 'home#terms'
  match '/promo_help' => 'home#promo_help'
  match '/promo_tabit' => 'home#promo_tabit'
  match '/promo_terms' => 'home#promo_terms'
  match '/promo_team' => 'home#promo_team'
  match '/promo_create' => 'home#promo_create'
  match '/promo_invite' => 'home#promo_invite'
  match '/promo_create' => 'feedback#promo_create'
  match '/index' => 'home#index'
  match 'js/bookmarkads' => 'Js#bookmarkads'
  match '/search' => 'search#search'
  match '/search_username' => 'users#search_username'
  match '/status_change/:id' => 'users#status_change', :as => "status_change"
  match '/status_unchange/:id' => 'users#status_unchange', :as => "status_unchange"
  match '/adminstatus_change/:id' => 'users#adminstatus_change', :as => "adminstatus_change"
  match '/adminstatus_unchange/:id' => 'users#adminstatus_unchange', :as => "adminstatus_unchange"
  match '/predictive_search' => 'search#predictive_search'
  match '/invite' => 'users#invite'
  match '/invite/email' => 'users#email'
 
  match '/setting/destroy_ads/:id' => 'settings#destroy_ads', :as => "destroy_ads"
  match '/setting/destroy_userscategories/:id' => 'settings#destroy_userscategories', :as => "destroy_userscategories"
  match '/setting/ignore_notification/:id' => 'settings#ignore_notification', :as => "ignore_ad"
  match '/setting/flag_ads' => 'settings#flag_ads'
  match '/setting' => 'settings#parameters'
  match '/setting/multipleuser' => 'settings#multipleuser'
  match '/setting/sort_username' => 'settings#sort_username'

  match '/setting/destroy_fbtw/:id' => 'settings#destroy_fbtw' , :as => "destroy_fbtw"
  match '/admin/edit' => 'settings#edit'
  match '/follow_brand' => 'users#follow_brand'
  match '/my_local_offers_without_category' => 'categories#my_local_offers_without_category'
  get '/category_list' => 'categories#category_list'
  get '/local_storage_data' => 'categories#local_storage_data'
  match '/search_offers' => 'ads#search_offers'
  get '/search_offer_by_brand' => 'offers#search_offer_by_brand'
  match '/search_ads' => 'ads#search_ads'
  post '/snapit', :to => 'ads#snapit'
  get '/scanit', :to => 'ads#scanit'
  post 'ad_fb_comment/:ad_id/:fb_comment_id' => 'ads#ad_fb_comment'
  get '/ads_show/:ad_id', :to => 'ads#ads_show'
  get '/omniauth_fb/:uid/:email' => 'settings#omniauth_fb'
  get '/omniauth_tw/:uid' => 'settings#omniauth_tw'
  #  resources :templates do
  #
  #  end
  resources :purposes

  match 'unsubscribe_me' => "registrations#unsubscribe"

  match "templates/delete_selection"=>"templates#delete_at_index"


  get '/home/render_div'=>'home#render_div'

  root :to=> 'home#about'
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  skip_before_filter :store_location
  before_filter :authenticate_user!, :except => [:omniauth_fb, :omniauth_tw]
  before_filter :admin_active, :only => [:edit]
  before_filter :authenticate_admin, :only => [:update,:edit]

  def omniauth_tw
    @auth_uid = Authentication.find_by_uid(params[:uid])
    unless @auth_uid.nil?
      @user = @auth_uid.user
      sign_in(@user)
      render :json => {:response => 'ok', :auth_token => @user.authentication_token}
    else
      render :json => {:error => 'No such user exists'}
    end
  end

  def omniauth_fb
    @auth_uid = Authentication.find_by_uid(params[:uid])
    
    unless @auth_uid.nil?
      @user = @auth_uid.user
      sign_in(@user)
      render :json => {:response => 'ok', :auth_token => @user.authentication_token}
    else
      render :json => {:error => 'No such user exists'}
    end
  end

  def parameters
    @setting = Setting.first
    respond_to do |format|
      format.json { render :json => @setting }
    end
  end
  
  def edit
    @setting = Setting.first
    if @setting.nil?
      @setting = Setting.new
    end      
    render 'edit', :layout => 'application'
  end
  def create
    @setting = Setting.new(params[:setting])
    if @setting.save
      redirect_to admin_edit_path
    end
  end
  
  def update
    @setting = Setting.first
    if params[:setting][:carousel_refresh].to_i >= 5 && @setting.update_attributes(params[:setting])
      flash[:notice] = 'Successfully update the settings'
      redirect_to admin_edit_path
    else
      flash[:notice] =  'Error while updating the settings, time interval cannot be less than 5 seconds'
      redirect_to admin_edit_path
    end
  end
 
 
  def users_list
    @user = User.all
    
    @users = User.search(params[:query])
    @u = User.all
    respond_to do |format|
      format.html { render 'users_list', :layout => 'admin' }
      format.xls
      format.js
    end
    
  end

  def new_users
    @user = User.new
    render 'new_users', :layout => 'admin'
  end
  
  def create_users 
    @user = User.new(params[:user])
    if params[:user][:admin] == "1"
      @user.admin = true
    else
      @user.admin = false
    end
    
    @user.skip_confirmation!

    if @user.save
      flash[:notice] = "User successfully created "
      #@user.confirm!
      redirect_to setting_users_list_path
    else
      flash[:notice] = "#{@user.errors.full_messages.join(', ')}"
      #render setting_new_users_path
      render :action=>'new_users', :message => @user , :layout => 'admin'
    end
  end
  
  def edit_users
    @user = User.find(params[:id])
    render 'edit_users', :layout => 'admin'
  end

  def show_users
    @user = User.find(params[:id])
    render 'show_users', :layout => 'admin'
  end

  def update_users
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    @user.save(validate: false)
    redirect_to setting_users_list_path
    flash[:notice] = "User successfully updated! "
  end

  def destroy_users
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      flash[:notice] = "User successfully deleted!"
      format.html { redirect_to(setting_users_list_path) }
    end
  end
  def multipleuser
    @user = User.find(params[:ids])
    @user.each { |u| u.destroy }
    flash[:notice] = "User successfully deleted!"
    redirect_to setting_users_list_path
  end
  def destroy_fbtw
    @authentication = Authentication.where("user_id = ?",params[:id].to_i)
    @authentication.destroy_all
    flash[:notice] = "Link removed"
    redirect_to setting_users_list_path
  end
  def sort_username
    @user = User.order("username ASC")#.page(params[:page]).per(7)
  end


  def allusersads
    if params[:grid_list] == 'list_clz'
      @listview = 'list_clz'
    elsif params[:grid_list] == 'grid_clz'
      @gridview = 'grid_clz'
    else
      @listview = 'list_clz'
    end
    @user = User.page(params[:page]).per(7)
    @ads = Ad.order("created_at desc").all
    respond_to do |format|
      format.html{ render :layout => "application"}
    end
  end	


  def destroy_ads
    @ad = Ad.find(params[:id])
    @ad.destroy
    respond_to do |format|
      flash[:notice] = "Offer successfully deleted!"
      format.html { redirect_to(setting_allusersads_path) }
    end
  end

  def destroy_userscategories
    @category = Category.find(params[:id])
    @category.destroy
    @group = Group.where("category_id = ?",@category.id)
    @group.each do|group|
      @ad = Ad.where("group_id = ?",group.id)
      group.destroy
      @ad.destroy_all
    end
    respond_to do |format|
      flash[:notice] = "Category successfully deleted!"
      format.html { redirect_to(setting_category_list_path) }
    end
  end

  def flag_ads
    @ads = Ad.where("flag = ?",true).page(params[:page]).per(7)
  end
  
  def multipleads
    @ad = Ad.find(params[:ids])
    @ad.each { |a| a.destroy }
    flash[:notice] = "Offer successfully deleted!"
    redirect_to setting_allusersads_path
  end
  
  def ignore_notification
    @ad = Ad.find(params[:id])
    @ad.update_attributes(:flag => false)
    @currentuser = current_user
    @user = User.admins
    @user.each do|user|
      UserMailer.ignore_status(@ad,@currentuser,user).deliver
    end
    flash[:notice] = "Offer successfully ignored!"
    redirect_to setting_allusersads_path
  end


  def category_list
    @category = Category.where('user_id IS NOT NULL and name not like ?','my saved fabtabs').page(params[:page]).per(7)
    respond_to do |format|
      format.html{render :layout => "admin"}
    end
  end
  
  def category_ads
    @category = Category.find(params[:id])
    @group =  Group.where("category_id = ?",@category.id)
    @group.each do|group|
      @ad = Ad.where("group_id = ?",group.id)
    end
    respond_to do |format|
      format.js
    end
  end
  def master_password
    @mpasswords = MasterPassword.first
    if @mpasswords.nil?
      @mpassword = MasterPassword.new
    else
      @mpasswords.mpassword = MasterPassword.decrypt
      @mpassword = @mpasswords
    end
    respond_to do |format|
      format.html { render :layout =>'application'}
    end
  end


  def new_mpassword
    @mpassword = MasterPassword.first
    respond_to do |format|
      if @mpassword.nil?
        @mpassword = MasterPassword.new(params[:master_password])
        if @mpassword.save
          format.html { redirect_to admin_edit_path, notice: 'Master Password was successfully created.' }
          format.json { render json: admin_edit_path, status: :created, location: admin_edit_path }
        else
          format.html { render action: "master_password",:layout =>'application' }
          format.json { render json: @mpassword.errors, status: :unprocessable_entity }
        end
      elsif @mpassword.update_attributes(params[:master_password])
        format.html { redirect_to admin_edit_path, notice: 'Master Password was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "master_password",:layout =>'application' }
        format.json { render json: @mpassword.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_listview_ads.html.erb
    <%= form_tag  setting_multipleads_path, :method => :delete do %>
      <table class="noborder">
      <% @ads.each do |ad|%>
        <tr>
          <td style="width: 24px;">
            <%= check_box_tag 'ids[]', ad.id, false ,:id => "ad_#{ad.id}",:class =>"user_cls"%>
          </td>
          <td style="padding-right: 10px; width: 60px;">
            <%= image_tag(ad.image_url,:width => "50",:height => "50") %>
          </td>
          <td style="width: 100px; padding-left: 2px; padding-right: 2px; height: 55px;">
            <% user = User.find_by_id(ad.user_id)  %>
            <%=  !user.nil? ? truncate(user.username, :length => 15, :omission => '...') : " " %>
          </td>
          <td style="width: 170px; padding-left: 10px; padding-right: 2px;">
            <% user = User.find_by_id(ad.user_id)  %>
            <%=   !user.nil? ? user.email: " " %>
          </td>
          <td style="padding-left: 5px; width: 100px; padding-right: 5px;">
            <% if ad.flag == true  %>
              YES
            <% else %>
              NO
            <%  end %>
          </td>
          <td style="border-right-width: 0px; padding-right: 3px; padding-left: 10px; width: 135px; border-left-width: 0px; margin-left: 0px;">
            <% if !ad.flagupdate.nil? %>
              <%= ad.flagupdate.strftime("%m/%d/%Y %I:%M%p") %>
            <% else %>
              <%= "N/A" %>
            <% end %>
          </td>
          <td style="width: 100px;">
            <%  if ad.flag == true && ad.status == true %>
              <%= link_to "Ignore", ignore_ad_path(ad.id) %>
            <% elsif ad.flag == true %>
             <%= link_to "Ignore", ignore_ad_path(ad.id) %>
            <% else %>
              N/A
            <% end %>
          </td>
          <td>
            <%= link_to "Delete", destroy_ads_path(ad.id), :method=>'delete' %>
          </td>
          <td style="width: 46px;">
            <div class="status" id="ads_<%= ad.id %>">
              <%= render :partial => "ads/ads_status", :locals => {:ad => ad } %>
            </div>
          </td>
        </tr>
      <% end %>
      <%= submit_tag "Delete",:id => "delete_all", :style => "margin-top: -71px;margin-left:-13px;" %>
      </table>
    <% end %>
<script>
  document.onload =  $("#delete_all").hide();
  $('#select_all').click(function() {
    if (this.checked) {
      $(':checkbox').each(function() {
        $("#delete_all").show();
        this.checked = true;
      });
    } else {
      $(':checkbox').each(function() {
        $("#delete_all").hide();
        this.checked = false;
      });
    }
  });
  var count=0;
  $('.user_cls').click(function() {
    if (this.checked) {
      count++;
      if(count > 0)
      {
        $("#delete_all").show();
      }
    }
    else
    {
      count--;
      if(count == 0)
      {
        $("#delete_all").hide();
      }
      else
      {
        $("#delete_all").show();
      }
    }
  });

$('.close').click(function(){
$('.close').parent().hide();
});
</script>

app/views/settings/_userslist.html.erb
<div class="tabal_div">
  <div class="row">
    <div class="check"><%= check_box_tag "user_id[]",@user ,false ,:id => "select_all"%></div>
    <div class="user_name" style="width: 138px;">User Name</div>
    <div class="email">Email</div>
    <div class="zipcode" style="text-align:left;">Zipcode</div>
    <div class="facebook" style="text-align:left;">Facebook</div>
    <div class="twitter" style="text-align:left;">Twitter</div>
    <div class="edit">&nbsp;</div>
    <div class="action" style="margin-left: -32px;">Actions</div>
    <div class="delete">&nbsp;</div>
    <div class="status" style="margin-left: 87px;">Status</div>
  </div>
  <div style="margin-top: -12px;height: 550px;overflow-x: hidden;overflow-y: scroll;width: 933px; float: left;" id="user_list1">
    <%= form_tag  setting_multipleuser_path, :method => :delete do %>
      <% @user.each do|user| %>
        <div class="row">
          <div class="check"><%= check_box_tag 'ids[]', user.id, false ,:id => "user_#{user.id}",:class =>"user_cls"%></div>
          <div class="user_name" style="width: 140px;">
            <% if user.username.nil? %>
              &nbsp;
            <% else %>
              <%= truncate(user.username, :length => 20, :omission=>'...') %>
            <% end %>
          </div>
          <div class="email"><%=  user.email %></div>
          <div class="zipcode" style="text-align:left;">
            <% if user.zipcode.nil? || user.zipcode.blank?%>
              &nbsp;
            <% else %>
              <%= truncate(user.zipcode, :length => 8, :omission=>'...') %>
            <% end %>
          </div>
          <div class="facebook" style="text-align:left;">
            <% @facebook = user.authentications.select { |authentication| authentication.provider == 'facebook' } %>
            <% if @facebook.empty? %>
              <%= link_to "N/A", '#' %>
            <% else %>
              <%= link_to "Remove Link", destroy_fbtw_path(user.id)%>
            <% end %>
          </div>
          <div class="twitter" style="text-align:left;">
            <% @twitter = user.authentications.select { |authentication| authentication.provider == 'twitter' } %>
            <% if @twitter.empty? %>
              <%= link_to "N/A", '#' %>
            <% else %>
              <%= link_to "Remove Link",destroy_fbtw_path(user.id) %>
            <% end %>
          </div>
          <div class="action">
            <%= link_to "View",show_users_path(user.id) %> |
          </div>
          <div class="edit"><%= link_to "Edit",edit_users_path(user.id) %> | </div>
          <div class="delete"><%= link_to "Delete","#",:onclick=>"show_delete_box(#{user.id})"  %> |
            <div class="delete_dialog hidden" id="hidden_delete_box_<%=  user.id %>" style="left: 135px;">
              <div class="close" style="margin: 12px 24px;">X</div>
              <div class="title" style="margin-left: 7px;"> Delete</div>
              <div class="message-text"> Delete this User?</div>
              <%= link_to "Delete", destroy_users_path(user.id), :method=>'delete', :class => 'delete_tab' %>
            </div>
          </div>

          <div class="admin" id="flag1_<%= user.id %>">
            <%= render :partial => "users/admin_status", :locals => {:user => user } %>
          </div>
          <div class="status" id="flag_<%= user.id %>" style="text-align: left;">
            <%= render :partial => "users/user_status", :locals => {:user => user } %>
          </div>
        </div>
      <% end %>
      <%= submit_tag "Delete",:id => "delete_all" , :style => "top:25px;position:absolute;"%>
    <% end %>
  </div>
</div>


<script type="text/javascript">   
  $(".delete").live('click',function(e) {
    e.preventDefault()
  });
  function show_delete_box(id){    
    $('#hidden_delete_box_'+id).css('display','block');      
  }


  document.onload =  $("#delete_all").hide();
  $('#select_all').click(function() {
    if (this.checked) {
      $(':checkbox').each(function() {
        $("#delete_all").show();
        this.checked = true;
      });
    } else {
      $(':checkbox').each(function() {
        $("#delete_all").hide();
        this.checked = false;
      });
    }
  });
  var count=0;
  $('.user_cls').click(function() {
    if (this.checked) {
      count++;
      if(count > 0)
      {
        $("#delete_all").show();
      }
    }
    else
    {
      count--;
      if(count == 0)
      {
        $("#delete_all").hide();
      }
      else
      {
        $("#delete_all").show();
      }
    }
  });
  $('.close').click(function(){
    $('.close').parent().hide();
  });


</script>
<style type="text/css">
  .delete_dialog {
    left: 135px;
    position: absolute;
    top: 26px;
    width: 230px;
    z-index: 10000004;
  }
</style>

app/views/settings/edit.html.erb
<div class="content">
  <div class="flash-message"></div>
  <%= form_for @setting do |f| %>
    <div classs="carousel-refersh-time">Carousel Refresh Time(in seconds)</div>
    <%= f.text_field :carousel_refresh %>
    <%= f.submit "Save", :id => "add_coupan" %>
  <% end %>


  <div class="brand-creation" style="margin-top: 12px;">
    <%= link_to "Create a Brand Category Folder", new_brand_path, :id => "add_coupan" %>
  </div>

  <div class="brand-requests">
    <%= link_to "User Requests for Brand Folders", brand_requests_path, :id => "add_coupan" %>
  </div>

  <div class="all-brands">
    <%= link_to "All Brand Folders", brands_path, :id => "add_coupan" %>
  </div>
  <div class="all-brands">
    <%= link_to "Manage Users", setting_users_list_path, :id => "add_coupan" %>
  </div>
  <div class="all-brands">
    <%= link_to "Manage Email Template",templates_path, :id => "add_coupan"%>
  </div>
  <div class="all-brands">
    <%= link_to "Manage Offers", setting_allusersads_path, :id => "add_coupan" %>
  </div>
  <div class="all-brands">
    <%= link_to "Export Users to XLS", setting_users_list_path(format: "xls"), :id => "add_coupan" %>
  </div>
  <div class="all-brands">
    <%= link_to "View User Stats" ,"https://www.google.com/analytics/web/?hl=en#home/a29789450w56039481p57113139/", :id => "add_coupan", :target => "_blank"%>
  </div>

  <div class="demo-creation">
<%#= link_to "Create a demo", new_demo_path, :id => "add_coupan" %>
<%#= link_to "All Demos",demos_path, :id => "add_coupan" %>
<%#= link_to "All Demo Ad images", demo_images_path, :id => "add_coupan"%>
  </div>

  <div class="backup">

<%= link_to "Create Back-up of Database", "/admin/run/dump" , :id=>"add_coupan" %>

<%= link_to "Download Database Dump File", db_path , :id=>"add_coupan" %>



  </div>
<br/>
<%= link_to "Master Password", master_password_path , :id=>"add_coupan" %>
</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29789450-1']);
  _gaq.push(['_trackPageview']);

  (function(){
    var ga = document.createElement('script'); ga.type =
      'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' :
      'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/settings/master_password.html.erb
  <%= link_to "Back",  admin_edit_path, :id=>"add_coupan", :style=>"float:right;margin-right: 2px;margin-top: 14px;" %>
<div class="content" style="float: none;">
  <div style="margin-top:45px;">
  <%= form_for(@mpassword,:url=> new_mpassword_path, :method=>'post') do |f| %>
    <% if @mpassword.errors.any? %>
      <% ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
        errors = Array(instance.error_message).join(',')
        %(#{html_tag}<span class="validation-error">&nbsp;#{errors}</span>).html_safe
      end %>
    <% end %>
    <div style="margin-bottom:10px; font-size: 18px;color: #939598;margin-top: -26px;margin-left:1px;">MASTER PASSWORD</div>
    <%= f.text_field :mpassword, :style=>'width: 190px;' %>
    <%= f.submit "Save", :id => "add_coupan" %>
  <% end %>

</div>
</div>
<style>
  .container footer {
    margin-top: 30px;
  }
</style>

app/views/settings/show_users.html.erb
<%= link_to "Edit",edit_users_path(@user.id),:id => "add_coupan", :style => "float: right;margin-top: -56px; margin-right: 83px;" %>
<%= link_to "Back",setting_users_list_path,:id => "add_coupan", :style => "float: right;margin-top: -56px; margin-right: 10px;" %>
<h2 style="font-size: 18px;color: #939598;font-weight: normal;">USER VIEW</h2>
<p>
  <b>User Name:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Zipcode:</b>
  <%= @user.zipcode %>
</p>

<p>
  <b>Number offers count:</b>
  <%= @user.offer_count %>
</p>

<p>
  <b>Super Folder Brand Count:</b>
  <%= @user.super_folder %>
</p>

<p>
  <b>Subscribe at:</b>
  <%if !@user.confirmed_at.nil?%>
  <%= @user.confirmed_at.strftime('%d-%^b-%Y %I:%M %p') %>
  <%else%>
  Not Yet Subscribed
  <%end%>
</p>

<p>
  <b>Brand Request Count:</b>
  <%= @user.brand_requests.count %>
</p>

app/views/settings/users_list.html.erb
<div style="margin-top: 37px;width:933px;height: 35px;margin-left:3px;font-size: 17px!important;">
  <span style="margin-right: 15px;font-size: 18px;color: #939598;">USER LIST</span>
<%= link_to "Top ","#",:style => "font-size: 18px;color: #939598;",:id => "totop" %><span style="color: #939598;">|</span>
  <%= link_to "Bottom ","#",:style => "font-size: 18px;color: #939598;",:id => "tobottom" %><span style="color: #939598;">|</span>
  <%= link_to "A-Z",setting_sort_username_path, :remote => "true" ,:style => "font-size: 18px;color: #939598;"%>
  <span style="float: right;margin-right: 12px;margin-top: -5px;">
    <% if MasterPassword.first %> <b>  Master Password: <%= MasterPassword.decrypt %> </b><% end %>
    <%= link_to "Add User",setting_new_users_path, :id => 'add_coupan' %>
    <%= link_to "Back",admin_edit_path, :id => 'add_coupan' %>
  </span>
</div>

<div id ="userslist">
  <br/><br/><br/>
  <%= render :partial => "settings/userslist", :locals => {:user => @user} %>
</div>
<%#*<div id="pagination_user">%>
<%#= paginate @user %>
<%#*</div>%>
<script type="text/javascript">
  $(function() {
    $('.pagination a').attr('data-remote', 'true');
  });
  $('#totop').live('click',function (e)
  {
    $('#user_list1').scrollTop("0") 
    // $('#user_list1').animate({         
    //     scrollTop: '0',
    //  }, 10000);
  });
  $('#tobottom').live('click',function (e)
  {
    $('#user_list1').scrollTop("10000")
   // $('#user_list1').animate({         
   //      scrollTop: '10000',
   //   }, 10000);
  });
</script>

<style type="text/css">
  .container footer {
    margin-top: 56px;
  }
</style>